---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-mshr-whisffee-net-v1-sspyfamilllly
  failurePolicy: Fail
  name: msspyfamilllly.kb.io
  rules:
  - apiGroups:
    - mshr.whisffee.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sspyfamillllies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mshr-whisffee-net-v1-sspyfamilllly
  failurePolicy: Fail
  name: vsspyfamilllly.kb.io
  rules:
  - apiGroups:
    - mshr.whisffee.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sspyfamillllies
  sideEffects: None
