version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --explicit_defaults_for_timestamp
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ftnw09
      MYSQL_PASSWORD: ftnw09
      MYSQL_DATABASE: ftnw09
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql:/var/lib/mysql:delegated
volumes:
  mysql:
